target_account_id = "222222222222"
target_region = "eu-west-1"
cross_account_role_name = "EC2ShutdownRole"
lambda_package_path = "../../lambda/ec2-shutdown-lambda.zip"
environment = "production"
schedule_expression = "cron(0 10 * * ? *)"
log_level = "INFO"
dry_run = "false"